# pyright: reportMissingModuleSource=false

from typing import assert_type

from pivy import coin


def check_action_application() -> None:
    root = coin.SoSeparator()
    cube = coin.SoCube()
    root.addChild(cube)
    path = coin.SoPath(root)
    path.append(0)
    paths = coin.SoPathList()
    paths.append(path)

    action = coin.SoCallbackAction()
    assert_type(action.apply(root), None)
    assert_type(action.apply(path), None)
    assert_type(action.apply(paths), None)
    assert_type(action.apply(paths, True), None)
    assert_type(action.hasTerminated(), bool)
    assert_type(action.getState(), coin.SoState)
    assert_type(action.getCurPath(), coin.SoPath)
    assert_type(action.getCurPathTail(), coin.SoNode)
    assert_type(action.getNodeAppliedTo(), coin.SoNode | None)
    assert_type(action.getPathAppliedTo(), coin.SoPath | None)
    assert_type(action.getPathListAppliedTo(), coin.SoPathList | None)
    assert_type(action.getOriginalPathListAppliedTo(), coin.SoPathList | None)

    action.pushCurPath()
    action.pushCurPath(0, cube)
    action.popPushCurPath(0)
    action.popCurPath()
    action.popCurPath(coin.SoAction.NODE)
    action.switchToNodeTraversal(root)
    action.switchToPathTraversal(path)


def check_callback_action_values() -> None:
    action = coin.SoCallbackAction()
    assert_type(action.getCoordinate3(0), coin.SbVec3f)
    assert_type(action.getCoordinate4(0), coin.SbVec4f)
    assert_type(action.getNormal(0), coin.SbVec3f)
    assert_type(action.getProfile(), coin.SoNodeList)
    assert_type(action.getTextureCoordinate2(0), coin.SbVec2f)
    assert_type(action.getTextureCoordinate3(0), coin.SbVec3f)
    assert_type(action.getTextureCoordinate4(0), coin.SbVec4f)
    assert_type(action.getTextureMatrix(), coin.SbMatrix)
    assert_type(action.getModelMatrix(), coin.SbMatrix)
    assert_type(action.getProjectionMatrix(), coin.SbMatrix)
    assert_type(action.getViewingMatrix(), coin.SbMatrix)
    assert_type(action.getViewVolume(), coin.SbViewVolume)
    assert_type(action.getViewportRegion(), coin.SbViewportRegion)
    assert_type(action.getMaterial(), tuple[coin.SbColor, coin.SbColor, coin.SbColor, coin.SbColor, float, float])
    assert_type(action.getCurrentResponse(), int)
    assert_type(action.isCallbackAll(), bool)


def check_search_action() -> None:
    search = coin.SoSearchAction()
    assert_type(search.getNode(), coin.SoNode | None)
    assert_type(search.getType(coin.intp()), coin.SoType)
    assert_type(search.getName(), coin.SbName)
    assert_type(search.getFind(), int)
    assert_type(search.getInterest(), int)
    assert_type(search.isSearchingAll(), bool)
    assert_type(search.getPath(), coin.SoPath | None)
    assert_type(search.getPaths(), coin.SoPathList)
    assert_type(search.isFound(), bool)

    search.setNode(coin.SoCube())
    search.setType(coin.SoCube.getClassTypeId())
    search.setName(coin.SbName("cube"))
    search.setFind(coin.SoSearchAction.ALL)
    search.setInterest(coin.SoSearchAction.LAST)
    search.setSearchingAll(True)
    search.setFound()
    search.addPath(coin.SoPath())
    search.reset()


def check_geometry_actions() -> None:
    viewport = coin.SbViewportRegion()
    root = coin.SoSeparator()

    bbox = coin.SoGetBoundingBoxAction(viewport)
    assert_type(bbox.getViewportRegion(), coin.SbViewportRegion)
    assert_type(bbox.getBoundingBox(), coin.SbBox3f)
    assert_type(bbox.getXfBoundingBox(), coin.SbXfBox3f)
    assert_type(bbox.getCenter(), coin.SbVec3f)
    assert_type(bbox.getResetPath(), coin.SoPath | None)
    assert_type(bbox.isResetPath(), bool)
    assert_type(bbox.isResetBefore(), bool)
    assert_type(bbox.isCenterSet(), bool)
    bbox.apply(root)
    bbox.extendBy(coin.SbBox3f())
    bbox.extendBy(coin.SbXfBox3f())

    matrix = coin.SoGetMatrixAction(viewport)
    assert_type(matrix.getViewportRegion(), coin.SbViewportRegion)
    assert_type(matrix.getMatrix(), coin.SbMatrix)
    assert_type(matrix.getInverse(), coin.SbMatrix)
    assert_type(matrix.getTextureMatrix(), coin.SbMatrix)
    assert_type(matrix.getTextureInverse(), coin.SbMatrix)
    matrix.apply(root)

    primitive = coin.SoGetPrimitiveCountAction()
    assert_type(primitive.getTriangleCount(), int)
    assert_type(primitive.getLineCount(), int)
    assert_type(primitive.getPointCount(), int)
    assert_type(primitive.containsNoPrimitives(), bool)
    assert_type(primitive.containsNonTriangleShapes(), bool)
    assert_type(primitive.canApproximateCount(), bool)
    primitive.apply(root)


def check_event_pick_and_write_actions() -> None:
    viewport = coin.SbViewportRegion()
    root = coin.SoSeparator()

    event = coin.SoHandleEventAction(viewport)
    assert_type(event.getViewportRegion(), coin.SbViewportRegion)
    assert_type(event.getEvent(), coin.SoEvent | None)
    assert_type(event.isHandled(), bool)
    assert_type(event.getGrabber(), coin.SoNode | None)
    assert_type(event.getPickRoot(), coin.SoNode | None)
    assert_type(event.getPickedPoint(), coin.SoPickedPoint | None)
    assert_type(event.getPickedPointList(), coin.SoPickedPointList)
    event.setEvent(coin.SoKeyboardEvent())
    event.setGrabber(root)
    event.setPickRoot(root)
    event.setHandled()
    event.releaseGrabber()

    pick = coin.SoRayPickAction(viewport)
    assert_type(pick.getPickedPoint(), coin.SoPickedPoint | None)
    assert_type(pick.getPickedPoint(0), coin.SoPickedPoint | None)
    assert_type(pick.getPickedPointList(), coin.SoPickedPointList)
    assert_type(pick.getViewVolume(), coin.SbViewVolume)
    assert_type(pick.getLine(), coin.SbLine)
    assert_type(pick.hasWorldSpaceRay(), bool)
    pick.setPoint(coin.SbVec2s(0, 0))
    pick.setNormalizedPoint(coin.SbVec2f(0.0, 0.0))
    pick.setRay(coin.SbVec3f(), coin.SbVec3f(0.0, 0.0, -1.0))
    pick.setPickAll(True)

    output = coin.SoOutput()
    write = coin.SoWriteAction(output)
    assert_type(write.getOutput(), coin.SoOutput)
    assert_type(write.continueToApply(root), None)


def check_render_action() -> None:
    action = coin.SoGLRenderAction(coin.SbViewportRegion())
    assert_type(action.getViewportRegion(), coin.SbViewportRegion)
    assert_type(action.getTransparencyType(), int)
    assert_type(action.isSmoothing(), bool)
    assert_type(action.getNumPasses(), int)
    assert_type(action.isPassUpdate(), bool)
    assert_type(action.getCacheContext(), int)
    assert_type(action.isRenderingDelayedPaths(), bool)
    assert_type(action.handleTransparency(), bool)
    assert_type(action.getCurPass(), int)
    assert_type(action.abortNow(), bool)
    assert_type(action.getRenderingIsRemote(), bool)
    assert_type(action.getSortedLayersNumPasses(), int)
    assert_type(action.getDelayedObjDepthWrite(), bool)
    assert_type(action.isRenderingTranspPaths(), bool)
    assert_type(action.isRenderingTranspBackfaces(), bool)
