# SPDX-License-Identifier: ISC
# Generated from local Pivy stubgen output; lightly normalized for checker use.

from _typeshed import Incomplete
from pivy.gui._soqt import cast as cast
from typing import ClassVar, Protocol, Sequence, overload
from types import BuiltinFunctionType as builtin_function_or_method
from pivy.coin import SbColor, SbVec2f, SbVec2s, SbVec3f, SbViewportRegion, SoCamera, SoDirectionalLight, SoEvent, SoGLRenderAction, SoNode, SoSceneManager, SoSelection, SoType

class SoQtComponentCallback(Protocol):
    def __call__(
        self, user: object, component: SoQtComponent, /
    ) -> None: ...

class SoQtViewerCallback(Protocol):
    def __call__(
        self, data: object, viewer: SoQtViewer, /
    ) -> None: ...

class SoQtRenderAreaCallback(Protocol):
    def __call__(self, data: object, event: QEvent, /) -> object: ...

class SoQtFatalErrorCallback(Protocol):
    def __call__(
        self, message: SbString, line: int, data: object, /
    ) -> None: ...

class SoQtAutoClippingCallback(Protocol):
    def __call__(
        self, data: object, value: SbVec2f, /
    ) -> SbVec2f: ...

class SoQtMenuSelectionCallback(Protocol):
    def __call__(self, menu_id: int, data: object, /) -> None: ...

class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    def __setattr__(cls, name: str, value: object) -> None: ...

class charp:
    __swig_destroy__: ClassVar[builtin_function_or_method] = ...
    thisown: bool
    def __init__(self) -> None: ...
    def assign(self, value: str) -> None: ...
    def value(self) -> str: ...
    def cast(self) -> object: ...
    @staticmethod
    def frompointer(t: object) -> charp: ...

class shortp:
    __swig_destroy__: ClassVar[builtin_function_or_method] = ...
    thisown: bool
    def __init__(self) -> None: ...
    def assign(self, value: int) -> None: ...
    def value(self) -> int: ...
    def cast(self) -> object: ...
    @staticmethod
    def frompointer(t: object) -> shortp: ...

class ushortp:
    __swig_destroy__: ClassVar[builtin_function_or_method] = ...
    thisown: bool
    def __init__(self) -> None: ...
    def assign(self, value: int) -> None: ...
    def value(self) -> int: ...
    def cast(self) -> object: ...
    @staticmethod
    def frompointer(t: object) -> ushortp: ...

class intp:
    __swig_destroy__: ClassVar[builtin_function_or_method] = ...
    thisown: bool
    def __init__(self) -> None: ...
    def assign(self, value: int) -> None: ...
    def value(self) -> int: ...
    def cast(self) -> object: ...
    @staticmethod
    def frompointer(t: object) -> intp: ...

class uintp:
    __swig_destroy__: ClassVar[builtin_function_or_method] = ...
    thisown: bool
    def __init__(self) -> None: ...
    def assign(self, value: int) -> None: ...
    def value(self) -> int: ...
    def cast(self) -> object: ...
    @staticmethod
    def frompointer(t: object) -> uintp: ...

class int8p:
    __swig_destroy__: ClassVar[builtin_function_or_method] = ...
    thisown: bool
    def __init__(self) -> None: ...
    def assign(self, value: int) -> None: ...
    def value(self) -> int: ...
    def cast(self) -> object: ...
    @staticmethod
    def frompointer(t: object) -> int8p: ...

class uint8p:
    __swig_destroy__: ClassVar[builtin_function_or_method] = ...
    thisown: bool
    def __init__(self) -> None: ...
    def assign(self, value: int) -> None: ...
    def value(self) -> int: ...
    def cast(self) -> object: ...
    @staticmethod
    def frompointer(t: object) -> uint8p: ...

class uint32p:
    __swig_destroy__: ClassVar[builtin_function_or_method] = ...
    thisown: bool
    def __init__(self) -> None: ...
    def assign(self, value: int) -> None: ...
    def value(self) -> int: ...
    def cast(self) -> object: ...
    @staticmethod
    def frompointer(t: object) -> uint32p: ...

class longp:
    __swig_destroy__: ClassVar[builtin_function_or_method] = ...
    thisown: bool
    def __init__(self) -> None: ...
    def assign(self, value: int) -> None: ...
    def value(self) -> int: ...
    def cast(self) -> object: ...
    @staticmethod
    def frompointer(t: object) -> longp: ...

class sizep:
    __swig_destroy__: ClassVar[builtin_function_or_method] = ...
    thisown: bool
    def __init__(self) -> None: ...
    def assign(self, value: int) -> None: ...
    def value(self) -> int: ...
    def cast(self) -> object: ...
    @staticmethod
    def frompointer(t: object) -> sizep: ...

class timep:
    __swig_destroy__: ClassVar[builtin_function_or_method] = ...
    thisown: bool
    def __init__(self) -> None: ...
    def assign(self, value: int) -> None: ...
    def value(self) -> int: ...
    def cast(self) -> object: ...
    @staticmethod
    def frompointer(t: object) -> timep: ...

class floatp:
    __swig_destroy__: ClassVar[builtin_function_or_method] = ...
    thisown: bool
    def __init__(self) -> None: ...
    def assign(self, value: float) -> None: ...
    def value(self) -> float: ...
    def cast(self) -> object: ...
    @staticmethod
    def frompointer(t: object) -> floatp: ...

class doublep:
    __swig_destroy__: ClassVar[builtin_function_or_method] = ...
    thisown: bool
    def __init__(self) -> None: ...
    def assign(self, value: float) -> None: ...
    def value(self) -> float: ...
    def cast(self) -> object: ...
    @staticmethod
    def frompointer(t: object) -> doublep: ...
FALSE: int
TRUE: int
HAVE_INTTYPES_H: int
HAVE_STDINT_H: int
HAVE_SYS_TYPES_H: int
HAVE_STDDEF_H: int
HAVE_INT8_T: int
HAVE_UINT8_T: int
HAVE_INT16_T: int
HAVE_UINT16_T: int
HAVE_INT32_T: int
HAVE_UINT32_T: int
HAVE_INT64_T: int
HAVE_UINT64_T: int
HAVE_INTPTR_T: int
HAVE_UINTPTR_T: int
M_E: float
M_LOG2E: float
M_LOG10E: float
M_LN2: float
M_LN10: float
M_PI: float
M_TWOPI: float
M_PI_2: float
M_PI_4: float
M_3PI_4: float
M_SQRTPI: float
M_1_PI: float
M_2_PI: float
M_2_SQRTPI: float
M_SQRT2: float
M_SQRT1_2: float
M_LN2LO: float
M_LN2HI: float
M_SQRT3: float
M_IVLN10: float
M_LOG2_E: float
M_INVLN2: float
COIN_MAJOR_VERSION: int
COIN_MINOR_VERSION: int
COIN_MICRO_VERSION: int
COIN_VERSION: str
HAVE_HASH_QUOTING: int
SUN_CC_4_0_SOTYPE_INIT_BUG: int

class QEvent:
    """Proxy of C++ QEvent class."""
    __swig_destroy__: ClassVar[builtin_function_or_method] = ...
    thisown: bool
    def __init__(self, *args, **kwargs) -> None: ...

class QWidget:
    """Proxy of C++ QWidget class."""
    __swig_destroy__: ClassVar[builtin_function_or_method] = ...
    thisown: bool
    def __init__(self, *args, **kwargs) -> None: ...
SOQT_MAJOR_VERSION: int
SOQT_MINOR_VERSION: int
SOQT_MICRO_VERSION: int
SOQT_VERSION: str
GUI_TOOLKIT_VERSION: str

class SoQtObject:
    """Proxy of C++ SoQtObject class."""
    __swig_destroy__: ClassVar[builtin_function_or_method] = ...
    thisown: bool
    def __init__(self, *args, **kwargs) -> None: ...
    @staticmethod
    def initClass() -> None: ...
    @staticmethod
    def getClassTypeId() -> SoType: ...
    def getTypeId(self) -> SoType: ...
    def isOfType(self, type: SoType) -> bool: ...
    @staticmethod
    def init() -> None: ...
SOQT_SUN_CC_4_0_SOTYPE_INIT_BUG: int

class SoQtDevice(SoQtObject):
    """Proxy of C++ SoQtDevice class."""
    __swig_destroy__: ClassVar[builtin_function_or_method] = ...
    thisown: bool
    def __init__(self, *args, **kwargs) -> None: ...
    @staticmethod
    def initClass() -> None: ...
    @staticmethod
    def getClassTypeId() -> SoType: ...
    def getTypeId(self) -> SoType: ...
    def enable(self, w: QWidget, handler: Incomplete, closure: Incomplete) -> None: ...
    def disable(self, w: QWidget, handler: Incomplete, closure: Incomplete) -> None: ...
    def translateEvent(self, event: QEvent) -> SoEvent: ...
    def setWindowSize(self, size: SbVec2s) -> None: ...
    def getWindowSize(self) -> SbVec2s: ...
    @staticmethod
    def initClasses() -> None: ...

class SoQtKeyboard(SoQtDevice):
    """Proxy of C++ SoQtKeyboard class."""
    KEY_PRESS: ClassVar[int] = ...
    KEY_RELEASE: ClassVar[int] = ...
    ALL_EVENTS: ClassVar[int] = ...
    __swig_destroy__: ClassVar[builtin_function_or_method] = ...
    thisown: bool
    @staticmethod
    def initClass() -> None: ...
    @staticmethod
    def getClassTypeId() -> SoType: ...
    def getTypeId(self) -> SoType: ...
    @staticmethod
    def createInstance() -> Incomplete: ...
    def __init__(self, eventmask: int = ...) -> None: ...
    def enable(self, widget: QWidget, handler: Incomplete, closure: Incomplete) -> None: ...
    def disable(self, widget: QWidget, handler: Incomplete, closure: Incomplete) -> None: ...
    def translateEvent(self, event: QEvent) -> SoEvent: ...

class SoQtMouse(SoQtDevice):
    """Proxy of C++ SoQtMouse class."""
    BUTTON_PRESS: ClassVar[int] = ...
    BUTTON_RELEASE: ClassVar[int] = ...
    POINTER_MOTION: ClassVar[int] = ...
    BUTTON_MOTION: ClassVar[int] = ...
    ALL_EVENTS: ClassVar[int] = ...
    __swig_destroy__: ClassVar[builtin_function_or_method] = ...
    thisown: bool
    @staticmethod
    def initClass() -> None: ...
    @staticmethod
    def getClassTypeId() -> SoType: ...
    def getTypeId(self) -> SoType: ...
    @staticmethod
    def createInstance() -> Incomplete: ...
    def __init__(self, eventmask: int = ...) -> None: ...
    def enable(self, widget: QWidget, handler: Incomplete, closure: Incomplete) -> None: ...
    def disable(self, widget: QWidget, handler: Incomplete, closure: Incomplete) -> None: ...
    def translateEvent(self, event: QEvent) -> SoEvent: ...

class SoQt:
    """Proxy of C++ SoQt class."""
    UNSPECIFIED_ERROR: ClassVar[int] = ...
    NO_OPENGL_CANVAS: ClassVar[int] = ...
    INTERNAL_ASSERT: ClassVar[int] = ...
    DLL: ClassVar[int] = ...
    LIB: ClassVar[int] = ...
    UNKNOWN: ClassVar[int] = ...
    thisown: bool
    def __init__(self, *args, **kwargs) -> None: ...
    @staticmethod
    @overload
    def init(appname: str, classname: str = ...) -> QWidget: ...
    @staticmethod
    @overload
    def init(argc: intp, argv: Sequence[str], appname: str, classname: str = ...) -> QWidget: ...
    @staticmethod
    @overload
    def init(toplevelwidget: QWidget) -> None: ...
    @staticmethod
    def exitMainLoop() -> None: ...
    @staticmethod
    def done() -> None: ...
    @staticmethod
    def getTopLevelWidget() -> QWidget: ...
    @staticmethod
    def getShellWidget(w: QWidget) -> QWidget: ...
    @staticmethod
    def show(widget: QWidget) -> None: ...
    @staticmethod
    def hide(widget: QWidget) -> None: ...
    @staticmethod
    def setWidgetSize(widget: QWidget, size: SbVec2s) -> None: ...
    @staticmethod
    def getWidgetSize(widget: QWidget) -> SbVec2s: ...
    @staticmethod
    def createSimpleErrorDialog(widget: QWidget, title: str, string1: str, string2: str | None = ...) -> None: ...
    @staticmethod
    def getVersionInfo(major: intp | None = ..., minor: intp | None = ..., micro: intp | None = ...) -> None: ...
    @staticmethod
    def getVersionString() -> str: ...
    @staticmethod
    def getVersionToolkitString() -> str: ...
    @staticmethod
    def setFatalErrorHandler(cb: SoQtFatalErrorCallback, userdata: object) -> SoQtFatalErrorCallback | None: ...
    @staticmethod
    def isDebugLibrary() -> bool: ...
    @staticmethod
    def isCompatible(major: int, minor: int) -> bool: ...
    @staticmethod
    def getABIType() -> int: ...
    @staticmethod
    def lockGL() -> None: ...
    @staticmethod
    def unlockGL() -> None: ...
    @staticmethod
    def mainLoop() -> None: ...

class SoQtComponent(SoQtObject):
    """Proxy of C++ SoQtComponent class."""
    __swig_destroy__: ClassVar[builtin_function_or_method] = ...
    thisown: bool
    def __init__(self, *args, **kwargs) -> None: ...
    @staticmethod
    def initClass() -> None: ...
    @staticmethod
    def getClassTypeId() -> SoType: ...
    def getTypeId(self) -> SoType: ...
    def show(self) -> None: ...
    def hide(self) -> None: ...
    def setComponentCursor(self, cursor: SoQtCursor) -> None: ...
    @staticmethod
    def setWidgetCursor(w: QWidget, cursor: SoQtCursor) -> None: ...
    def isFullScreen(self) -> bool: ...
    def setFullScreen(self, onoff: bool) -> bool: ...
    def isVisible(self) -> bool: ...
    def isTopLevelShell(self) -> bool: ...
    def getWidget(self) -> QWidget: ...
    def getBaseWidget(self) -> QWidget: ...
    def getShellWidget(self) -> QWidget: ...
    def getParentWidget(self) -> QWidget: ...
    def setSize(self, size: SbVec2s) -> None: ...
    def getSize(self) -> SbVec2s: ...
    def setTitle(self, title: str) -> None: ...
    def getTitle(self) -> str: ...
    def setIconTitle(self, title: str) -> None: ...
    def getIconTitle(self) -> str: ...
    def getWidgetName(self) -> str: ...
    def getClassName(self) -> str: ...
    def setWindowCloseCallback(self, func: SoQtComponentCallback, user: object | None = ...) -> None: ...
    @staticmethod
    def getComponent(widget: QWidget) -> SoQtComponent: ...
    @staticmethod
    def initClasses() -> None: ...
SO_GL_RGB: int
SO_GLX_RGB: int
SO_GL_DOUBLE: int
SO_GLX_DOUBLE: int
SO_GL_ZBUFFER: int
SO_GLX_ZBUFFER: int
SO_GL_OVERLAY: int
SO_GLX_OVERLAY: int
SO_GL_STEREO: int
SO_GLX_STEREO: int

class SoQtGLWidget(SoQtComponent):
    """Proxy of C++ SoQtGLWidget class."""
    thisown: bool
    def __init__(self, *args, **kwargs) -> None: ...
    @staticmethod
    def initClass() -> None: ...
    @staticmethod
    def getClassTypeId() -> SoType: ...
    def getTypeId(self) -> SoType: ...
    def setBorder(self, enable: bool) -> None: ...
    def isBorder(self) -> bool: ...
    def setDoubleBuffer(self, enable: bool) -> None: ...
    def isDoubleBuffer(self) -> bool: ...
    def setDrawToFrontBufferEnable(self, enable: bool) -> None: ...
    def isDrawToFrontBufferEnable(self) -> bool: ...
    def setQuadBufferStereo(self, enable: bool) -> None: ...
    def isQuadBufferStereo(self) -> bool: ...
    def setAccumulationBuffer(self, enable: bool) -> None: ...
    def getAccumulationBuffer(self) -> bool: ...
    def setStencilBuffer(self, enable: bool) -> None: ...
    def getStencilBuffer(self) -> bool: ...
    def setAlphaChannel(self, enable: bool) -> None: ...
    def getAlphaChannel(self) -> bool: ...
    def setOverlayRender(self, onoff: bool) -> None: ...
    def isOverlayRender(self) -> bool: ...
    def setSampleBuffers(self, numsamples: int) -> None: ...
    def getSampleBuffers(self) -> int: ...
    def setStealFocus(self, enable: bool) -> None: ...
    def isStealFocus(self) -> bool: ...
    def getGLWidget(self) -> QWidget: ...
    def getNormalWidget(self) -> QWidget: ...
    def getOverlayWidget(self) -> QWidget: ...
    def hasOverlayGLArea(self) -> bool: ...
    def hasNormalGLArea(self) -> bool: ...
    def getOverlayTransparentPixel(self) -> int: ...
    def getPointSizeLimits(self, range: SbVec2f, granularity: floatp) -> None: ...
    def getLineWidthLimits(self, range: SbVec2f, granularity: floatp) -> None: ...

class SoQtRenderArea(SoQtGLWidget):
    """Proxy of C++ SoQtRenderArea class."""
    __swig_destroy__: ClassVar[builtin_function_or_method] = ...
    thisown: bool
    @staticmethod
    def initClass() -> None: ...
    @staticmethod
    def getClassTypeId() -> SoType: ...
    def getTypeId(self) -> SoType: ...
    @staticmethod
    def createInstance() -> Incomplete: ...
    def __init__(self, parent: QWidget | None = ..., name: str | None = ..., embed: bool = ..., mouseInput: bool = ..., keyboardInput: bool = ...) -> None: ...
    def setSceneGraph(self, scene: SoNode) -> None: ...
    def getSceneGraph(self) -> SoNode | None: ...
    def setOverlaySceneGraph(self, scene: SoNode) -> None: ...
    def getOverlaySceneGraph(self) -> SoNode | None: ...
    def setBackgroundColor(self, color: SbColor) -> None: ...
    def getBackgroundColor(self) -> SbColor: ...
    def setBackgroundIndex(self, idx: int) -> None: ...
    def getBackgroundIndex(self) -> int: ...
    def setOverlayBackgroundIndex(self, idx: int) -> None: ...
    def getOverlayBackgroundIndex(self) -> int: ...
    def setColorMap(self, start: int, num: int, colors: SbColor) -> None: ...
    def setOverlayColorMap(self, start: int, num: int, colors: SbColor) -> None: ...
    def setViewportRegion(self, newRegion: SbViewportRegion) -> None: ...
    def getViewportRegion(self) -> SbViewportRegion: ...
    def setTransparencyType(self, type: int) -> None: ...
    def getTransparencyType(self) -> int: ...
    def setAntialiasing(self, smoothing: bool, numPasses: int) -> None: ...
    def getAntialiasing(self, smoothing: intp, numPasses: intp) -> None: ...
    def setClearBeforeRender(self, enable: bool, zbEnable: bool = ...) -> None: ...
    def isClearBeforeRender(self) -> bool: ...
    def isClearZBufferBeforeRender(self) -> bool: ...
    def setClearBeforeOverlayRender(self, enable: bool) -> None: ...
    def isClearBeforeOverlayRender(self) -> bool: ...
    def setAutoRedraw(self, enable: bool) -> None: ...
    def isAutoRedraw(self) -> bool: ...
    def setRedrawPriority(self, priority: int) -> None: ...
    def getRedrawPriority(self) -> int: ...
    @staticmethod
    def getDefaultRedrawPriority() -> int: ...
    def render(self) -> None: ...
    def renderOverlay(self) -> None: ...
    def scheduleRedraw(self) -> None: ...
    def scheduleOverlayRedraw(self) -> None: ...
    def redrawOnSelectionChange(self, selection: SoSelection) -> None: ...
    def redrawOverlayOnSelectionChange(self, selection: SoSelection) -> None: ...
    def setSceneManager(self, manager: SoSceneManager) -> None: ...
    def getSceneManager(self) -> SoSceneManager: ...
    def setOverlaySceneManager(self, manager: SoSceneManager) -> None: ...
    def getOverlaySceneManager(self) -> SoSceneManager: ...
    def setGLRenderAction(self, action: SoGLRenderAction) -> None: ...
    def getGLRenderAction(self) -> SoGLRenderAction: ...
    def setOverlayGLRenderAction(self, action: SoGLRenderAction) -> None: ...
    def getOverlayGLRenderAction(self) -> SoGLRenderAction: ...
    def sendSoEvent(self, event: SoEvent) -> bool: ...
    def registerDevice(self, device: SoQtDevice) -> None: ...
    def unregisterDevice(self, device: SoQtDevice) -> None: ...
    def setEventCallback(self, pyfunc: SoQtRenderAreaCallback, user: object | None = ...) -> None: ...

class SoQtViewer(SoQtRenderArea):
    """Proxy of C++ SoQtViewer class."""
    BROWSER: ClassVar[int] = ...
    EDITOR: ClassVar[int] = ...
    VIEW_AS_IS: ClassVar[int] = ...
    VIEW_HIDDEN_LINE: ClassVar[int] = ...
    VIEW_NO_TEXTURE: ClassVar[int] = ...
    VIEW_LOW_COMPLEXITY: ClassVar[int] = ...
    VIEW_LINE: ClassVar[int] = ...
    VIEW_POINT: ClassVar[int] = ...
    VIEW_BBOX: ClassVar[int] = ...
    VIEW_LOW_RES_LINE: ClassVar[int] = ...
    VIEW_LOW_RES_POINT: ClassVar[int] = ...
    VIEW_SAME_AS_STILL: ClassVar[int] = ...
    VIEW_WIREFRAME_OVERLAY: ClassVar[int] = ...
    STILL: ClassVar[int] = ...
    INTERACTIVE: ClassVar[int] = ...
    BUFFER_SINGLE: ClassVar[int] = ...
    BUFFER_DOUBLE: ClassVar[int] = ...
    BUFFER_INTERACTIVE: ClassVar[int] = ...
    VARIABLE_NEAR_PLANE: ClassVar[int] = ...
    CONSTANT_NEAR_PLANE: ClassVar[int] = ...
    STEREO_NONE: ClassVar[int] = ...
    STEREO_ANAGLYPH: ClassVar[int] = ...
    STEREO_QUADBUFFER: ClassVar[int] = ...
    STEREO_INTERLEAVED_ROWS: ClassVar[int] = ...
    STEREO_INTERLEAVED_COLUMNS: ClassVar[int] = ...
    thisown: bool
    def __init__(self, *args, **kwargs) -> None: ...
    @staticmethod
    def initClass() -> None: ...
    @staticmethod
    def getClassTypeId() -> SoType: ...
    def getTypeId(self) -> SoType: ...
    def setCamera(self, camera: SoCamera) -> None: ...
    def getCamera(self) -> SoCamera | None: ...
    def setCameraType(self, type: SoType) -> None: ...
    def getCameraType(self) -> SoType: ...
    def toggleCameraType(self) -> None: ...
    def viewAll(self) -> None: ...
    def saveHomePosition(self) -> None: ...
    def resetToHomePosition(self) -> None: ...
    def setHeadlight(self, enable: bool) -> None: ...
    def isHeadlight(self) -> bool: ...
    def getHeadlight(self) -> SoDirectionalLight: ...
    def setDrawStyle(self, type: int, style: int) -> None: ...
    def getDrawStyle(self, type: int) -> int: ...
    def setBufferingType(self, type: int) -> None: ...
    def getBufferingType(self) -> int: ...
    def setViewing(self, enable: bool) -> None: ...
    def isViewing(self) -> bool: ...
    def setCursorEnabled(self, enable: bool) -> None: ...
    def isCursorEnabled(self) -> bool: ...
    def setAutoClipping(self, enable: bool) -> None: ...
    def isAutoClipping(self) -> bool: ...
    def setAutoClippingStrategy(self, strategy: int, value: float = ..., cb: SoQtAutoClippingCallback | None = ..., cbuserdata: object | None = ...) -> None: ...
    def setStereoViewing(self, enable: bool) -> None: ...
    def isStereoViewing(self) -> bool: ...
    def setStereoOffset(self, dist: float) -> None: ...
    def getStereoOffset(self) -> float: ...
    def setStereoType(self, s: int) -> bool: ...
    def getStereoType(self) -> int: ...
    def setAnaglyphStereoColorMasks(self, left: Sequence[bool], right: Sequence[bool]) -> None: ...
    def getAnaglyphStereoColorMasks(self, left: Incomplete, right: Incomplete) -> None: ...
    def setDetailSeek(self, enable: bool) -> None: ...
    def isDetailSeek(self) -> bool: ...
    def setSeekTime(self, seconds: float) -> None: ...
    def getSeekTime(self) -> float: ...
    def addStartCallback(self, func: SoQtViewerCallback, data: object | None = ...) -> None: ...
    def addFinishCallback(self, func: SoQtViewerCallback, data: object | None = ...) -> None: ...
    def removeStartCallback(self, func: SoQtViewerCallback, data: object | None = ...) -> None: ...
    def removeFinishCallback(self, func: SoQtViewerCallback, data: object | None = ...) -> None: ...
    def setWireframeOverlayColor(self, color: SbColor) -> None: ...
    def getWireframeOverlayColor(self) -> SbColor: ...
    def setDoubleBuffer(self, enable: bool) -> None: ...
    def setSceneGraph(self, root: SoNode) -> None: ...
    def getSceneGraph(self) -> SoNode | None: ...

class SoQtFullViewer(SoQtViewer):
    """Proxy of C++ SoQtFullViewer class."""
    BUILD_NONE: ClassVar[int] = ...
    BUILD_DECORATION: ClassVar[int] = ...
    BUILD_POPUP: ClassVar[int] = ...
    BUILD_ALL: ClassVar[int] = ...
    thisown: bool
    def __init__(self, *args, **kwargs) -> None: ...
    @staticmethod
    def initClass() -> None: ...
    @staticmethod
    def getClassTypeId() -> SoType: ...
    def getTypeId(self) -> SoType: ...
    def setDecoration(self, on: bool) -> None: ...
    def isDecoration(self) -> bool: ...
    def setPopupMenuEnabled(self, on: bool) -> None: ...
    def isPopupMenuEnabled(self) -> bool: ...
    def getAppPushButtonParent(self) -> QWidget: ...
    def addAppPushButton(self, newButton: QWidget) -> None: ...
    def insertAppPushButton(self, newButton: QWidget, index: int) -> None: ...
    def removeAppPushButton(self, oldButton: QWidget) -> None: ...
    def findAppPushButton(self, oldButton: QWidget) -> int: ...
    def lengthAppPushButton(self) -> int: ...
    def getRenderAreaWidget(self) -> QWidget: ...
    def setViewing(self, on: bool) -> None: ...
    def setComponentCursor(self, cursor: SoQtCursor) -> None: ...

class SoQtPlaneViewer(SoQtFullViewer):
    """Proxy of C++ SoQtPlaneViewer class."""
    __swig_destroy__: ClassVar[builtin_function_or_method] = ...
    thisown: bool
    @staticmethod
    def initClass() -> None: ...
    @staticmethod
    def getClassTypeId() -> SoType: ...
    def getTypeId(self) -> SoType: ...
    @staticmethod
    def createInstance() -> Incomplete: ...
    def __init__(self, parent: QWidget | None = ..., name: str | None = ..., embed: bool = ..., flag: int = ..., type: int = ...) -> None: ...
    def setViewing(self, enable: bool) -> None: ...
    def setCamera(self, camera: SoCamera) -> None: ...
    def setCursorEnabled(self, enable: bool) -> None: ...

class SoQtExaminerViewer(SoQtFullViewer):
    """Proxy of C++ SoQtExaminerViewer class."""
    __swig_destroy__: ClassVar[builtin_function_or_method] = ...
    thisown: bool
    @staticmethod
    def initClass() -> None: ...
    @staticmethod
    def getClassTypeId() -> SoType: ...
    def getTypeId(self) -> SoType: ...
    @staticmethod
    def createInstance() -> Incomplete: ...
    def __init__(self, parent: QWidget | None = ..., name: str | None = ..., embed: bool = ..., flag: int = ..., type: int = ...) -> None: ...
    def setAnimationEnabled(self, enable: bool) -> None: ...
    def isAnimationEnabled(self) -> bool: ...
    def stopAnimating(self) -> None: ...
    def isAnimating(self) -> bool: ...
    def setFeedbackVisibility(self, enable: bool) -> None: ...
    def isFeedbackVisible(self) -> bool: ...
    def setFeedbackSize(self, size: int) -> None: ...
    def getFeedbackSize(self) -> int: ...
    def setViewing(self, enable: bool) -> None: ...
    def setCamera(self, camera: SoCamera) -> None: ...
    def setCursorEnabled(self, enable: bool) -> None: ...

class SoQtConstrainedViewer(SoQtFullViewer):
    """Proxy of C++ SoQtConstrainedViewer class."""
    thisown: bool
    def __init__(self, *args, **kwargs) -> None: ...
    @staticmethod
    def initClass() -> None: ...
    @staticmethod
    def getClassTypeId() -> SoType: ...
    def getTypeId(self) -> SoType: ...
    def setUpDirection(self, dir: SbVec3f) -> None: ...
    def getUpDirection(self) -> SbVec3f: ...
    def setCamera(self, newcam: SoCamera) -> None: ...
    def saveHomePosition(self) -> None: ...
    def resetToHomePosition(self) -> None: ...

class SoQtFlyViewer(SoQtConstrainedViewer):
    """Proxy of C++ SoQtFlyViewer class."""
    __swig_destroy__: ClassVar[builtin_function_or_method] = ...
    thisown: bool
    @staticmethod
    def initClass() -> None: ...
    @staticmethod
    def getClassTypeId() -> SoType: ...
    def getTypeId(self) -> SoType: ...
    @staticmethod
    def createInstance() -> Incomplete: ...
    def __init__(self, parent: QWidget | None = ..., name: str | None = ..., embed: bool = ..., flag: int = ..., type: int = ...) -> None: ...
    def setViewing(self, enable: bool) -> None: ...
    def viewAll(self) -> None: ...
    def resetToHomePosition(self) -> None: ...
    def setCamera(self, camera: SoCamera) -> None: ...
    def setCursorEnabled(self, enable: bool) -> None: ...
    def setCameraType(self, type: SoType) -> None: ...

class SoQtPopupMenu:
    """Proxy of C++ SoQtPopupMenu class."""
    __swig_destroy__: ClassVar[builtin_function_or_method] = ...
    thisown: bool
    def __init__(self, *args, **kwargs) -> None: ...
    @staticmethod
    def createInstance() -> SoQtPopupMenu: ...
    def newMenu(self, name: str, menuid: int = ...) -> int: ...
    def getMenu(self, name: str) -> int: ...
    def setMenuTitle(self, id: int, title: str) -> None: ...
    def getMenuTitle(self, id: int) -> str: ...
    def newMenuItem(self, name: str, itemid: int = ...) -> int: ...
    def getMenuItem(self, name: str) -> int: ...
    def setMenuItemTitle(self, itemid: int, title: str) -> None: ...
    def getMenuItemTitle(self, itemid: int) -> str: ...
    def setMenuItemEnabled(self, itemid: int, enabled: bool) -> None: ...
    def getMenuItemEnabled(self, itemid: int) -> bool: ...
    def setMenuItemMarked(self, itemid: int, marked: bool) -> None: ...
    def getMenuItemMarked(self, itemid: int) -> bool: ...
    def addMenu(self, menuid: int, submenuid: int, pos: int = ...) -> None: ...
    def addMenuItem(self, menuid: int, itemid: int, pos: int = ...) -> None: ...
    def addSeparator(self, menuid: int, pos: int = ...) -> None: ...
    def removeMenu(self, menuid: int) -> None: ...
    def removeMenuItem(self, itemid: int) -> None: ...
    def popUp(self, inside: QWidget, x: int, y: int) -> None: ...
    def newRadioGroup(self, groupid: int = ...) -> int: ...
    def getRadioGroup(self, itemid: int) -> int: ...
    def getRadioGroupSize(self, groupid: int) -> int: ...
    def addRadioGroupItem(self, groupid: int, itemid: int) -> None: ...
    def removeRadioGroupItem(self, itemid: int) -> None: ...
    def setRadioGroupMarkedItem(self, itemid: int) -> None: ...
    def getRadioGroupMarkedItem(self, groupid: int) -> int: ...
    def addMenuSelectionCallback(self, callback: SoQtMenuSelectionCallback, data: object) -> None: ...
    def removeMenuSelectionCallback(self, callback: SoQtMenuSelectionCallback, data: object) -> None: ...

class SoQtCursor:
    """Proxy of C++ SoQtCursor class."""
    CUSTOM_BITMAP: ClassVar[int] = ...
    DEFAULT: ClassVar[int] = ...
    BUSY: ClassVar[int] = ...
    CROSSHAIR: ClassVar[int] = ...
    UPARROW: ClassVar[int] = ...
    __swig_destroy__: ClassVar[builtin_function_or_method] = ...
    thisown: bool
    @staticmethod
    def initClass() -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, shape: int) -> None: ...
    @overload
    def __init__(self, cc: int) -> None: ...
    @overload
    def __init__(self, cursor: SoQtCursor) -> None: ...
    def getShape(self) -> int: ...
    def setShape(self, shape: int) -> None: ...
    def getCustomCursor(self) -> int: ...
    @staticmethod
    def getZoomCursor() -> SoQtCursor: ...
    @staticmethod
    def getPanCursor() -> SoQtCursor: ...
    @staticmethod
    def getRotateCursor() -> SoQtCursor: ...
    @staticmethod
    def getBlankCursor() -> SoQtCursor: ...
