"""Canonical registries for class-specific Pivy factory policies."""

from __future__ import annotations


# Keep the order stable: runtime tests use this tuple to exercise every
# factory, while the set is used by the stub-generation policy.
ENGINE_FACTORY_CLASS_NAMES = (
    "SoBoolOperation",
    "SoCalculator",
    "SoComposeVec2f",
    "SoComposeVec3f",
    "SoComposeVec4f",
    "SoDecomposeVec2f",
    "SoDecomposeVec3f",
    "SoDecomposeVec4f",
    "SoComposeRotation",
    "SoDecomposeRotation",
    "SoComposeMatrix",
    "SoDecomposeMatrix",
    "SoComposeRotationFromTo",
    "SoComputeBoundingBox",
    "SoConcatenate",
    "SoCounter",
    "SoElapsedTime",
    "SoGate",
    "SoInterpolateFloat",
    "SoInterpolateVec2f",
    "SoInterpolateVec3f",
    "SoInterpolateVec4f",
    "SoInterpolateRotation",
    "SoOnOff",
    "SoOneShot",
    "SoSelectOne",
    "SoTimeCounter",
    "SoTransformVec3f",
    "SoTriggerAny",
    "SoHeightMapToNormalMap",
    "SoVRMLColorInterpolator",
    "SoVRMLCoordinateInterpolator",
    "SoVRMLNormalInterpolator",
    "SoVRMLOrientationInterpolator",
    "SoVRMLPositionInterpolator",
    "SoVRMLScalarInterpolator",
    "SoVRMLTimeSensor",
)

ENGINE_FACTORY_CLASSES = frozenset(ENGINE_FACTORY_CLASS_NAMES)


SCXML_FACTORY_CLASS_NAMES = (
    "SoScXMLDollyTarget",
    "SoScXMLFlightControlTarget",
    "SoScXMLMiscTarget",
    "SoScXMLMotionTarget",
    "SoScXMLPanTarget",
    "SoScXMLRotateTarget",
    "SoScXMLSeekTarget",
    "SoScXMLSpinTarget",
    "SoScXMLZoomTarget",
    "ScXMLAnchorElt",
    "ScXMLAssignElt",
    "ScXMLStringDataObj",
    "ScXMLRealDataObj",
    "ScXMLBoolDataObj",
    "ScXMLSbDataObj",
    "ScXMLXMLDataObj",
    "ScXMLReferenceDataObj",
    "ScXMLAndOpExprDataObj",
    "ScXMLOrOpExprDataObj",
    "ScXMLNotOpExprDataObj",
    "ScXMLEqualsOpExprDataObj",
    "ScXMLAddOpExprDataObj",
    "ScXMLSubtractOpExprDataObj",
    "ScXMLMultiplyOpExprDataObj",
    "ScXMLDivideOpExprDataObj",
    "ScXMLNegateOpExprDataObj",
    "ScXMLCoinEvaluator",
    "ScXMLCoinEqualsOpExprDataObj",
    "ScXMLCoinAddOpExprDataObj",
    "ScXMLCoinSubtractOpExprDataObj",
    "ScXMLCoinMultiplyOpExprDataObj",
    "ScXMLCoinDivideOpExprDataObj",
    "ScXMLCoinLengthFuncExprDataObj",
    "ScXMLContentElt",
    "ScXMLDataElt",
    "ScXMLDataModelElt",
    "ScXMLDocument",
    "ScXMLECMAScriptEvaluator",
    "ScXMLElseElt",
    "ScXMLElseIfElt",
    "ScXMLEvent",
    "ScXMLEventElt",
    "ScXMLFinalElt",
    "ScXMLFinalizeElt",
    "ScXMLHistoryElt",
    "ScXMLIfElt",
    "ScXMLInitialElt",
    "ScXMLInvokeElt",
    "ScXMLLogElt",
    "ScXMLMinimumEvaluator",
    "ScXMLOnEntryElt",
    "ScXMLOnExitElt",
    "ScXMLParallelElt",
    "ScXMLParamElt",
    "ScXMLScxmlElt",
    "ScXMLSendElt",
    "ScXMLStateElt",
    "ScXMLStateMachine",
    "ScXMLTransitionElt",
    "ScXMLValidateElt",
    "ScXMLXPathEvaluator",
    "SoScXMLEvent",
    "SoScXMLStateMachine",
)

SCXML_FACTORY_CLASSES = frozenset(SCXML_FACTORY_CLASS_NAMES)

# Coin 4.0.7 exposes these factories, but their runtime type IDs are not
# initialized consistently, so autocasting them would return ScXMLObject (or
# emit registration errors). Keep them explicitly outside the adapted set
# until the upstream runtime contract is fixed.
SCXML_UNSUPPORTED_FACTORY_CLASS_NAMES = (
    "ScXMLInExprDataObj",
    "ScXMLAppendOpExprDataObj",
    "ScXMLScriptElt",
)
